---
GLOBAL_DATA_DIR: '/home/chunyu_sys/workspace/cy_ansible/data'
CA_DIR: '/home/chunyu_sys/workspace/cy_ansible/data/ca'


limits_enabled: yes
limits_path: /etc/security/limits.conf

# configure /etc/limits
limits_limits:
  - '* soft nofile 100000'
  - '* hard nofile 100000'

# configure /etc/sysctl.conf,  auto reload
limits_sysctl:
  - { name: 'net.ipv4.tcp_fin_timeout', value: '1' }
  - { name: 'net.ipv4.tcp_keepalive_time', value: '30' }
  - { name: 'net.ipv4.tcp_keepalive_probes', value: '2' }
  - { name: 'net.ipv4.tcp_keepalive_intvl', value: '2' }
  - { name: 'net.ipv4.tcp_syncookies', value: '1' }
  - { name: 'net.ipv4.tcp_tw_reuse', value: '1' }
  - { name: 'net.ipv4.tcp_tw_recycle', value: '1' }
  - { name: 'net.ipv4.tcp_timestamps', value: '0' }
  - { name: 'net.ipv4.ip_local_port_range', value: '1024 65000' }
  - { name: 'net.ipv4.route.gc_timeout', value: '100' }
  - { name: 'net.ipv4.tcp_syn_retries', value: '1' }
  - { name: 'net.ipv4.tcp_synack_retries', value: '1' }
  - { name: 'net.ipv4.tcp_max_tw_buckets', value: '20000' }
  - { name: 'net.core.somaxconn', value: '65535' }
  - { name: 'net.core.netdev_max_backlog', value: '262144' }
  - { name: 'net.ipv4.tcp_max_orphans', value: '262144' }
  - { name: 'net.ipv4.tcp_max_syn_backlog', value: '262144' }
  - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
  - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
#  - { name: 'net.ipv6.conf.all.disable_ipv6', value: '1' }
#  - { name: 'net.ipv6.conf.default.disable_ipv6', value: '1' }
  - { name: 'vm.swappiness', value: '0' }
  - { name: 'net.ipv4.ip_forward', value: '1'}
  # 开启并记录欺骗，源路由和重定向包
  - { name: 'net.ipv4.conf.all.log_martians', value: '1' }
  - { name: 'net.ipv4.conf.default.log_martians', value: '1' }

# configure /etc/pam.d/
limits_pamd_files:
  - 'login'
